### ISSUE TITLE
Install v1 and cant open the site

### ISSUE THREAD

**Issue by louis-l** [vitodeploy/vito#136]
**Describe the bug**
Install fresh Vito onto Vultr instance. After the installation is completed, cannot access the dashboard by opening server's IP address. 
Got "took too long to respond" error.

**To Reproduce**
Steps to reproduce the behavior: described above

**Expected behavior**
Can see the Vito dashboard

**Comment by saeedvaziry** [comment]
@louis-l Please check the nginx logs.
/var/log/nginx/error.log

**Comment by tomaklod** [comment]
@louis-l 
The problem is from the port 80 not open in Vultr instance, you just have to open it with :
`iptables -A INPUT -p tcp --dport 80 -j ACCEPT`

It works for me

**Comment by louis-l** [comment]
Thanks, I was working on something else, will give this a try soon.
