### ISSUE TITLE
Disconnect from Server

### ISSUE THREAD

**Issue by erenergul** [vitodeploy/vito#141]
I installed vito and add custom server successfully. After that try to create new site but I waited too long 0%. So i try to delete website and reinstall but couldn't delete either. No error in laravel.log

I clicked reboot now i disconnect from server. Can not connect again. How to connect again? I dont want to wait installation process again and what if disconnect again in the future ? not sure why its disconnect ?

**Comment by saeedvaziry** [comment]
@erenergul when you reboot the server it will disconnect of course. then after a few minutes, you need to click the check connection to get connected again.
if it is not connecting then try via your terminal to ssh to the server.

I will need more info to understand your case.

**Comment by erenergul** [comment]
@saeedvaziry I dont understand the situation very well as well. After few minutes i tried everything didnt connect at all. I install locally.  I can connect to terminal ssh. but when i try add server nothing happened. Its stuck 0%.  

what do you need to understand because its empty log. I install vito successfully. I reinstall server to install again but doesnt work either.

**Comment by saeedvaziry** [comment]
Are you using Docker or Vito installed on a virtual machine?
If docker then please restart the container.
If a virtual machine then please restart the supervisor with the following command:
```sh
sudo supervisorctl restart worker:*
```

**Comment by erenergul** [comment]
Im using laravel valet.

**Comment by saeedvaziry** [comment]
Then you need to make sure the queues are running.
```sh
php artisan queue:work --sleep=3 --timeout=0
```

**Comment by erenergul** [comment]
Yes i tried that but nothing happened. No queue when i try to add server. I think its not normal.

**Comment by saeedvaziry** [comment]
Anything on the storage/logs/laravel.log ?

**Comment by erenergul** [comment]
I had an error from beginning probably but in that time i successfully installed server. 

```
[2024-03-18 18:08:55] local.ERROR: The process "'/opt/homebrew/Cellar/php/8.2.11/bin/php' 'artisan' 'queue:work' '--once' '--name=default' '--queue=default,ssh,ssh-long' '--backoff=0' '--memory=128' '--sleep=3' '--tries=1'" exceeded the timeout of 600 seconds. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"'/opt/homebrew/Cellar/php/8.2.11/bin/php' 'artisan' 'queue:work' '--once' '--name=default' '--queue=default,ssh,ssh-long' '--backoff=0' '--memory=128' '--sleep=3' '--tries=1'\" exceeded the timeout of 600 seconds. at /Users/erenergul/www/vito/vendor/symfony/process/Process.php:1156)
[stacktrace]
```

Its 10 days ago when i add server. I think its break something.

**Comment by saeedvaziry** [comment]
Could you try with recommended installation? Laravel Sail
https://vitodeploy.com/introduction/installation.html#laravel-sail

**Comment by erenergul** [comment]
Okay. Let me try with sail and docker. Thank you for your help. Btw Its really good idea to get an answer , If you create discord channel. Please consider it. Its really good application. Thats why i want to try to use it.

**Comment by saeedvaziry** [comment]
We already have a discord channel :)
Feel free to join
https://discord.gg/dcUWA5DV

**Comment by erenergul** [comment]
Thank you but invitation doesn't work. If you update it. I would like to join :)

**Comment by saeedvaziry** [comment]
ok thats the reason less people joined the channel haha

https://discord.gg/uZeeHZZnm5

**Comment by saeedvaziry** [comment]
Closing the issue and leaving a guide for such cases:

Some steps to follow to see how it goes:
- Stop the queue
- refresh migration: `php artisan migrate:refresh`
- and then the following commands to clear route and cache and views:

```
php artisan cache:clear
php artisan config:clear
php artisan view:clear
php artisan key:generate
```

And finally to create a new user
`./vendor/bin/sail artisan user:create {name} {email} {password}`


And then delete the containers 

and boot up the app again (if using sail. if not re-run workers)
`./vendor/bin/sail up -d`
