### ISSUE TITLE
.env save bug

### ISSUE THREAD

**Issue by clashshot** [vitodeploy/vito#142]
![image](https://github.com/vitodeploy/vito/assets/12329772/9629bb53-1917-469c-a06d-6f66b086b9ef)

![image](https://github.com/vitodeploy/vito/assets/12329772/68fab744-9ad1-49d6-9bc8-8e07ee169ae1)

Error "production.ERROR: App\SSH\OS\OS::editFile(): Argument #2 ($content) must be of type string, null given, called in /home/vito/vito/app/Actions/Site/UpdateEnv.php on line 11 {"userId":1,"exception":"[object] (TypeError(code: 0): App\\SSH\\OS\\OS::editFile(): Argument #2 ($content) must be of type string, null given, called in /home/vito/vito/app/Actions/Site/UpdateEnv.php on line 11 at /home/vito/vito/app/SSH/OS/OS.php:101)"

**Comment by clashshot** [comment]
Doesn't matter if i save it empty or with correct .env, both fails.

**Comment by saeedvaziry** [comment]
Are you using docker?

**Comment by clashshot** [comment]
Nope, installed directly on the server.

**Comment by saeedvaziry** [comment]
I could reproduce the first part (the empty one) and for the editor problem in my case it is trying to load over HTTP but my domain is https
