### ISSUE TITLE
Site Sorting

### ISSUE THREAD

**Issue by ebenwatts** [vitodeploy/vito#143]
I will be glad if you introduce site sorting on the "sites page". For example, I currently have 9 websites on my server and I want some sites to be at the top, or you can introduce site pinning! You can pin your favourite (most active) sites at the top.

**Comment by saeedvaziry** [comment]
I believe this is not a common usage. here is my alternative suggestion.
We can introduce Favorite/Pinned search results in the search popup.
This is still a raw idea, will think more on this but its not prio at the moment.

**Comment by ebenwatts** [comment]
Sure, any best option

**Comment by maxcelos** [comment]
Hey guys, just to add a small contribution in this discussion, for my use case pin/favorite would not be that useful, but I'm really missing a label field and simple sorting to have the related sites close to each other.

This could solve the pin feature by just adding a number as prefix in the label.

For example:
1 - Label here
1 - Some label
Another label - prod
Another label - dev
CMS site label - prod
CMS site label - dev
P-label test
Zlabel app

**Comment by saeedvaziry** [comment]
I think the label/tag feature would make sense here. not only for the sites but also for the servers.

**Comment by devsarfo** [comment]
Any plans for this task?

**Comment by saeedvaziry** [comment]
@devsarfo busy with other stuff. would be nice if someone could takeover.

**Comment by saeedvaziry** [comment]
Will close this with merging #277 feature. the next step will be adding filters based on tags
