### ISSUE TITLE
Is there a way to migrate from forge.laravel.com ?

### ISSUE THREAD

**Issue by gaetan-hexadog** [vitodeploy/vito#15]
Hi,

Thanks a lot for this wonderful project.

Is there a way to migrate a server currently managed by forge.laravel.com to VitoDeploy ?
I would like to use an existing server without having to reinstall it and all the websites.

Regards,

**Comment by gaetan-hexadog** [comment]
Thanks for your quick answer.

Will it work if I just add my existing forge managed server into vito ?

**Comment by saeedvaziry** [comment]
well, it would be tricky if you wanna do like that as the users of the OS will be different.

at the end you might need to do a migration from existing server to the new one.

but all the OS requirements for an app is being prepared by Vito. So you might wanna try to build your new server alongside the one that is working with Vito and move the data once to see if you can. you might need to keep your droplets running for a couple of hours during this test.
