### ISSUE TITLE
SSL on and Vhost Update Issue and SSL Install Alias

### ISSUE THREAD

**Issue by erenergul** [vitodeploy/vito#160]
Letsencrypt does not use anymore ssl on. So it needs to remove from Vhost file when its generated ssl. 

ssl on; 

nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/domain.com:7
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

It doesn't break when you dont use non-www but when you use any alias. It breaks your ssl and bring first website ssl cert on your server every www alias. 

SSL seems doesnt work with alias

Please need to check alias installation ssl. 

And 

Vhost update doesnt work on site settings.  Keep coming same data when you update it.

**Comment by saeedvaziry** [comment]
@erenergul vhost update already fixed with the latest release 1.3.0

**Comment by saeedvaziry** [comment]
@erenergul after next release vito will also get SSL for aliases and automatically set them in the vhost.
