### ISSUE TITLE
Add Domain Alias Section

### ISSUE THREAD

**Issue by erenergul** [vitodeploy/vito#161]
This is from other panel i use long time but I want to see this in vito deploy as well. Its really helpful part for me. Please consider it. 

<img width="700" alt="ekran-resmi" src="https://github.com/vitodeploy/vito/assets/23069775/cca01661-7118-4737-ad1d-84a8ad72a724">

**Comment by saeedvaziry** [comment]
At the moment you can add new alias by manually updating the vhost file in the site settings.

Updating vhost has a bug that will be fixed on #164
