### ISSUE TITLE
Error on clean install

### ISSUE THREAD

**Issue by wrtisans** [vitodeploy/vito#17]
i got this errors on clean install on ubuntu 22 
![CleanShot 2023-08-24 at 23 27 36](https://github.com/vitodeploy/vito/assets/44764875/37c78f59-9747-45b4-af33-c2314bcedd73)
![CleanShot 2023-08-24 at 23 28 19](https://github.com/vitodeploy/vito/assets/44764875/633787a2-81f7-4c22-93d0-085e36c0082f)

**Comment by saeedvaziry** [comment]
Just installed it and worked fine.

Could you please share with which command you're installing (passing any ENV or not)?

If you still have the server, which version of composer has been installed there?

**Comment by saeedvaziry** [comment]
Are you trying to install it on a docker container?

**Comment by wrtisans** [comment]
No, Proxmox Containers, also known as LXC (Linux Containers), offer a lightweight virtualization method that runs processes with isolation and without the need to emulate hardware or fully install a guest operating system.

https://www.wundertech.net/proxmox-container-lxc/

**Comment by saeedvaziry** [comment]
Haven't tested it on Proxmox Containers.

**Comment by wrtisans** [comment]
so, it's only compatible with vm and not container?
