### ISSUE TITLE
Add local storage provider

### ISSUE THREAD

**Issue by saeedvaziry** [vitodeploy/vito#182]
### Discussed in https://github.com/vitodeploy/vito/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **alexanderzeillinger** April 24, 2024</sup>
For DB backups I would like to be able to save them on the server itself.</div>

**Comment by alexanderzeillinger** [comment]
Thanks!

I find the description text confusing:
"The absolute path on your server that the database exists."

Shouldn't that be something like:
"The absolute path on your server where the backup will be stored."
