### ISSUE TITLE
Billing System

### ISSUE THREAD

**Issue by SiFuMax09** [vitodeploy/vito#189]
Add a billing system to sell the management. Like Laravel Forge does it. For this also a registration system is necessary.

Ideas:

- Plans
   - Creatable Plans from Admin Account: Servers and site limit
   - Add option to resell the servers or let the user connect an API to it
- Add branding options. Like color and logo and name.

**Comment by saeedvaziry** [comment]
Vito is not designed to serve business needs but to simplify server management for Developers and System admins for FREE.
