### ISSUE TITLE
git auto deployment

### ISSUE THREAD

**Issue by spartyboy** [vitodeploy/vito#196]
git auto deployment failing even after i used keys to pull successfully from github, all permissions are enabled as well
[2024-05-08 19:06:57] production.ERROR: Validation Failed {"userId":1,"exception":"[object] (App\\Exceptions\\FailedToDeployGitHook(code: 0): Validation Failed at /home/vito/vito/app/SourceControlProviders/Github.php:69)

**Comment by saeedvaziry** [comment]
@spartyboy does it have the hooks permissions?

**Comment by spartyboy** [comment]
> @spartyboy does it have the hooks permissions?

yes also is there a way i manually pull update from git, and any sample of a deployment script?

**Comment by saeedvaziry** [comment]
Are you using Vito on a server or local? if it is local it might not work because Github requires an internet URL so it can send webhooks in case of any pushes.

**Comment by saeedvaziry** [comment]
> and any sample of a deployment script?

we don't have a sample deployment script. you can write your own and save it into the deployment script and run the deployment.

**Comment by spartyboy** [comment]
its on a server but running local as the ip is tunneled via cloudflare and i don't know how to point vito or create a domain for vito as that option is no longer available

**Comment by saeedvaziry** [comment]
Check this

https://vitodeploy.com/introduction/securing.html

**Comment by spartyboy** [comment]
can vito make use of a .yml file just like in cpanel an a button to pull repository

**Comment by saeedvaziry** [comment]
You can just put a command into the deployment script like `git pull` and then click the Deploy button. it will do it :)

**Comment by saeedvaziry** [comment]
https://vitodeploy.com/sites/application.html
