### ISSUE TITLE
404 Error on deleting project

### ISSUE THREAD

**Issue by maxcelos** [vitodeploy/vito#207]
**Describe the bug**
After confirm on deleting project modal, it redirects to page `settings/projects/delete/{id}` that returns 404

**To Reproduce**
1. Go to Projects list
2. Click on delete icon
3. In the confirmation modal, click in Delete button
4. See the error

**Expected behavior**
Delete project and refresh the projects list

**Screenshots**
n/a

**Additional context**
Same error for current project or not

**Comment by saeedvaziry** [comment]
@maxcelos 

- How many projects do you have in the list when you face the error?
- Do you have a current project selected when the error happens?
- Does the user that deletes the project have access to the all projects in the list? (or is it an admin?)

**Comment by saeedvaziry** [comment]
I see the problem. The reason is your user (the admin one) doesn't have the project in his permissions. But it shouldn't be like that because it is an admin.

Next PR will fix the issue
