### ISSUE TITLE
Improve Console output format

### ISSUE THREAD

**Issue by alexanderzeillinger** [vitodeploy/vito#209]
Only 2 CSS rules for a much better formatting:

`font-family: monospace;
    white-space: pre;`

Before

![image](https://github.com/vitodeploy/vito/assets/126621/d06d3f3c-028d-49cb-8a12-f17bd2dca45a)

After

![image](https://github.com/vitodeploy/vito/assets/126621/a1269d98-19f9-44eb-b8f5-26ef981a9d64)

**Comment by saeedvaziry** [comment]
@alexanderzeillinger agreed! would you open the PR?
