### ISSUE TITLE
Server settings available updates error 500

### ISSUE THREAD

**Issue by alexanderzeillinger** [vitodeploy/vito#210]
**Describe the bug**
Shows empty brackets and when I click on "Check" there is an error 500

**To Reproduce**
1. Go to Server Settings
2. Click on Check

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/vitodeploy/vito/assets/126621/e279468c-bfb5-4e83-b65e-42ec0baccaff)

**Comment by saeedvaziry** [comment]
@alexanderzeillinger check your storage/logs/laravel.log file

**Comment by alexanderzeillinger** [comment]
`[2024-05-15 19:19:04] production.ERROR: SQLSTATE[HY000]: General error: 1 no such column: updates (Connection: sqlite, SQL: update "servers" set "updates" = 49, "last_update_check" = 2024-05-15 19:19:04, "updated_at" = 2024-05-15 19:19:04 where "id" = 3) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1 no such column: updates (Connection: sqlite, SQL: update \"servers\" set \"updates\" = 49, \"last_update_check\" = 2024-05-15 19:19:04, \"updated_at\" = 2024-05-15 19:19:04 where \"id\" = 3) at /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[stacktrace]`

**Comment by saeedvaziry** [comment]
Looks like the update command didn't work correctly. do you have the logs of the update script?

if not maybe you can run the update again

**Comment by alexanderzeillinger** [comment]
I ran the migrations manually, now the missing columns are there, solved.
