### ISSUE TITLE
Error 500 when trying to edit a SourceControl

### ISSUE THREAD

**Issue by maxcelos** [vitodeploy/vito#211]
**Describe the bug**
After update to version 1.6.0 and trying to see the SourceControl edit feature, it returns error 500

**To Reproduce**
1. Go to 'Source Controls'
2. Click on Edit button
3. See error

**Expected behavior**
See the source control info and edit it.

**Screenshots**
n/a

**Additional context**

**Comment by saeedvaziry** [comment]
@maxcelos any error logs? from `storage/logs/laravel.log`

**Comment by maxcelos** [comment]
Route not found.

Solved with `php artisan route:clear`
