### ISSUE TITLE
Use selected PHP version on site creation to run composer install

### ISSUE THREAD

**Issue by maxcelos** [vitodeploy/vito#214]
When creating a new site with the "Run composer install --no-dev" flag, it runs with default php cli, ignoring the php version selected in the form. It should use the selected php version.

Composer install command should be like this, for PHP8.2: 
```
php8.2 /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
```

Those two changes below should do the trick. No time to test right now, but if someone have already the setup to contribute please feel free to send the PR.

![CleanShot 2024-05-15 at 17 49 11](https://github.com/vitodeploy/vito/assets/15364289/f23275ef-00b8-4558-9a43-1e59c66d8051)

![CleanShot 2024-05-15 at 17 49 31](https://github.com/vitodeploy/vito/assets/15364289/59c3a137-c5a0-4d0d-b348-7973511dd388)

**Comment by devsarfo** [comment]
I could take this one if no one has started it. @saeedvaziry should I go ahead?

**Comment by saeedvaziry** [comment]
@devsarfo 💪
