### ISSUE TITLE
vito shows 404 on site creation

### ISSUE THREAD

**Issue by spartyboy** [vitodeploy/vito#225]
vito shows 404 when i attempted to create site http://193.124.205.64/

**Comment by saeedvaziry** [comment]
@spartyboy I need more info to reproduce.

what was the exact inputs when you created the site?

**Comment by spartyboy** [comment]
> @spartyboy I need more info to reproduce.
> 
> what was the exact inputs when you created the site?

i created as php blank added domain and saved

**Comment by spartyboy** [comment]
> > @spartyboy I need more info to reproduce.
> > what was the exact inputs when you created the site?
> 
> i created as php blank added domain and saved

kindly try installing vito on a server afresh and create a php blank project it would first start throwing 502 then next you see is file not found pop up done this four times rn.. pls revert to previous version as this has issues

**Comment by spartyboy** [comment]
> @spartyboy I need more info to reproduce.
> 
> what was the exact inputs when you created the site?

i feel this issue has to do with nginx config

**Comment by saeedvaziry** [comment]
I will try to reproduce.

in the meantime please also share the vhost config you have on the site settings

**Comment by saeedvaziry** [comment]
I tried to reproduce with the info you shared. after creating the site I face with 403 error and it is because of the blank PHP site doesn't create anything there.

so I created an index.php file there via the deployment script and it was working fine.

**Comment by spartyboy** [comment]
> I tried to reproduce with the info you shared. after creating the site I faced with 403 error and it is because of the blank PHP site doesn't create anything there.
> 
> so I created an index.php file there via the deployment script and it was working fine.

i am getting a 404 at my end i can show you if there is a means of contact. really not sure why

**Comment by saeedvaziry** [comment]
@spartyboy is the domain correctly pointed to the server? maybe you can check with the DNS checkers. also if using cloudflare make sure you have the proxy off to directly connect to the domain to make sure it points correctly

**Comment by austinkregel** [comment]
👋🏻 Hello, I've been going through the project's code and doing my best to get the lay of the land.

To the best of my knowledge this seems like intended functionality. Vito, by default, is accessible only via the domain based on the nginx config. 

Every request that isn't on the domain will be caught by the `catch-all` rule that's configured at `/etc/nginx/sites-enabled/catch-all`.

@spartyboy :eyes: are you wanting assistance on changing your configuration to allow Vito to be accessible via the direct IP? Or are you suggesting the default behavior be changed?

If you'd like to change your configuration to be accessible via IP directly you can do so by changing the `/etc/nginx/sites-enabled/vito` file; 

Specifically, you'll need to update the `server_name` part to include the public IP of the server. 

By default it should be configured to the domain you set up during installation. If we change the line to read as `server_name DOMAIN IP;` it'll allow your Vito instance to be accessed via IP, or the domain you configured You can learn more about different `server_name` configurations via [Nginx's docs](https://nginx.org/en/docs/http/server_names.html#miscellaneous_names)

**Comment by spartyboy** [comment]
> @spartyboy is the domain correctly pointed to the server? maybe you can check with the DNS checkers. also if using cloudflare make sure you have the proxy off to directly connect to the domain to make sure it points correctly

it is hold am attaching a video soon

**Comment by spartyboy** [comment]
> I tried to reproduce with the info you shared. after creating the site I faced with 403 error and it is because of the blank PHP site doesn't create anything there.
> 
> so I created an index.php file there via the deployment script and it was working fine.


Uploading VID-20240606-WA0041(1).mp4…
Here is the cideo

**Comment by austinkregel** [comment]
@spartyboy no video uploaded 🙈 would you be able to update the video?

**Comment by spartyboy** [comment]
> > I tried to reproduce with the info you shared. after creating the site I faced with 403 error and it is because of the blank PHP site doesn't create anything there.
> > so I created an index.php file there via the deployment script and it was working fine.
> 
> Uploading VID-20240606-WA0041(1).mp4… Here is the video


https://github.com/vitodeploy/vito/assets/26467959/bd4038e4-2e1a-492e-8f07-f2c72056b323

**Comment by saeedvaziry** [comment]
@spartyboy Oh I see now! Looks like you've used VitoDeploy's server itself to deploy your sites. Thats why it breaks it.

Check here #158
