### ISSUE TITLE
Log not show

### ISSUE THREAD

**Issue by moskoweb** [vitodeploy/vito#229]
**Describe the bug**
I uploaded a Vito application via Docker, to test, and I tried to install WordPress 3 times and it returned an error, 1 time when creating the database and 2 times when restarting PHP, but it is not possible to see the error, why is the log is blank.
**To Reproduce**
1. Go to Sites
2. Create new site WordPress
3. Error in instalation
4. Try see error

**Expected behavior**

**Screenshots**
![CleanShot 2024-06-06 at 11 54 03@2x](https://github.com/vitodeploy/vito/assets/6052272/84a450df-2654-4823-9614-ef12fad34870)

**Additional context**

**Comment by saeedvaziry** [comment]
@moskoweb can we close this? as your PR already merged #237

**Comment by saeedvaziry** [comment]
Open a new issue if it is still failing.
