### ISSUE TITLE
php.ini not updated in wordpress site type install

### ISSUE THREAD

**Issue by acidlake** [vitodeploy/vito#246]
**Describe the bug**
If you install the wordpress site and then edit the php version in vito deployment ui and do changes like, max_upload_size, even after you restart the services, you don't see the changes, i need it to login to the VPS on which my apps and sites are installed and edit the php manually.

**To Reproduce**
1. Go to Sites
2. Click on create site
3. Choose a wordpress site on the type
4. Fill the properties like you normally do
5. Wait for the server to provision
6. Go to your new site
7. Login to your wordpress admin with the credentials
8. Go to media and upload a new file with size bigger than 2MB
9. Go to your Deploy dashboard
10. Choose the server on which you installed your wordpress site
11. Go to PHP and edit your php.ini
12. Save and restart your services
13. Go again to your wordpress site admin panel
14. Go to upload a Media above 2MB
15. See error

**Expected behavior**
If i change any PHP options in vito deploy dashboard i expect that the wordpress site php.ini get updated too, in laravel it works great.

**Comment by saeedvaziry** [comment]
This is not a bug!

The reason is VitoDeploy updates the php.ini of php-cli

But I think we should also be able to update the php.ini of php-fpm
