### ISSUE TITLE
instal my apps in the same server with vito

### ISSUE THREAD

**Issue by hugo-abdou** [vitodeploy/vito#25]
i install this dashboard and its working on my ip directly without domain  thats fin my problem is 
how to create my websites in the same server i'm using to host the dashbord

**Comment by hugo-abdou** [comment]
@saeedvaziry so i'm forced to by new server to install my apps

**Comment by saeedvaziry** [comment]
@hugo-abdou keep in mind that you can boot up the VitoDeploy on your local to manage your severs :)
