### ISSUE TITLE
Vito Agent Memory Reporting Free Memory as Used Memory

### ISSUE THREAD

**Issue by devsarfo** [vitodeploy/vito#250]
**Describe the bug**
When you are using the Vito Agent, it reports the Used Memory as the Free Memory and Vice Versa

**To Reproduce**
1. Install the Vito Agent for Monitoring
2. View the Metrics and observe the Memory
3. Uninstall the Vito Agent and Install Remote Monitor
4. View the Metrics and observe the Memory for both monitors

**Screenshots**

Using Vito Agent
<img width="1080" alt="vito-agent" src="https://github.com/vitodeploy/vito/assets/20325487/e95319f5-6708-41ef-9917-2b5c6f08fc9b">

Using Remote Monitor
<img width="1096" alt="remote-monitor" src="https://github.com/vitodeploy/vito/assets/20325487/27c3a373-9d36-4619-aa26-d370d1316f0e">

**Additional context**

The Remote Monitor returns the right values for the Memory. I have looked into the code for the Vito Agent and realised the issue is from the case "MemAvailable":

<img width="591" alt="image" src="https://github.com/vitodeploy/vito/assets/20325487/231ec3fd-74e0-4ef8-8f59-9a80585bed56">

I can go ahead and make a PR to fix that if you agree.

**Comment by devsarfo** [comment]
Fixed with PRs [#1](https://github.com/vitodeploy/agent/pull/1) and [#2](https://github.com/vitodeploy/agent/pull/1) in the agent. 

![image](https://github.com/vitodeploy/vito/assets/20325487/a1750dec-ea3e-4dc4-b788-6c0f161f1ef7)

Can we close this now @saeedvaziry?

**Comment by saeedvaziry** [comment]
Cool. Thanks @devsarfo
