### ISSUE TITLE
SSH command failed with an error

### ISSUE THREAD

**Issue by rafa-acioly** [vitodeploy/vito#257]
**Describe the bug**
When trying to create a database the error "SSH command failed with an error" shows up, the error do not have a connection status as the error handling suggest:

> SSH command failed with an error

```SSH.php
if ($this->connection->getExitStatus() !== 0 || Str::contains($output, 'VITO_SSH_ERROR')) {
     throw new SSHCommandError('SSH command failed with an error', $this->connection->getExitStatus());
}
```

**To Reproduce**
1. Add a new SSH key with "ssh-keygen" on the server
2. Go to Server SSH keys page
3. Click on Add New key
4. Past the generated SSH key and save it
5. Go to Databases page
6. Click on Create Database
7. Give it a name and click Create
8. see the error...

**Screenshots**

<img width="1203" alt="Captura de Tela 2024-07-26 às 16 54 33" src="https://github.com/user-attachments/assets/c31091a9-a2bf-4eee-b0ff-3b8787d668aa">

**Comment by saeedvaziry** [comment]
With the first step, you're overriding the ssh key that VitoDeploy has deployed to the server.
