### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by ErasmoDev** [vitodeploy/vito#26]
I think it`s good feature add suport for postgreSQL too, many devs use it. I`m making a API (SAAS) basead on Schemas Databases and mysql don`t have it, only posgtesSQL.
 I will be happy to use this project to manager my server/APIs if having support for postgreSQL.
..^_^..

**Comment by saeedvaziry** [comment]
Added to the roadmap

https://features.vitodeploy.com/submissions/659309940be3e19e9437f7f3
