### ISSUE TITLE
How to restart PHP-FPM from deplopyment script ?

### ISSUE THREAD

**Issue by gaetan-hexadog** [vitodeploy/vito#270]
Hi,

how can I restart PHP-FPM from a deployment script ? 

regards

**Comment by saeedvaziry** [comment]
You can just run a command in your script to restart

```
sudo systemctl restart phpX-X-fpm
```

**Comment by gaetan-hexadog** [comment]
But running a cmd with `sudo` will ask for the password ! No ?

**Comment by saeedvaziry** [comment]
@gaetan-hexadog `vito` user has enough permissions, it should not ask for password.
