### ISSUE TITLE
Deploy succeeds when there are merge conflicts

### ISSUE THREAD

**Issue by Dennis4720** [vitodeploy/vito#273]
**Describe the bug**
Deploy succeeds when there are merge conflicts

**To Reproduce**
1. Get merge conflict: ```* branch acc -> FETCH_HEAD
a502f64..69a697c acc -> origin/acc
error: Your local changes to the following files would be overwritten by merge:
composer.lock```
2. Vito says deploy succeeds

**Expected behavior**
Show a failed deploy and stop deploy script on failed part.

**Screenshots**

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/35467b38-b76a-43e8-a590-fd8e60b92e43">

**Comment by saeedvaziry** [comment]
@Dennis4720 can you share the deployment script?

**Comment by Dennis4720** [comment]
```
# git
cd $SITE_PATH
git pull origin $BRANCH

composer update --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

# npm
cd $SITE_PATH/public/assets
if [[ ! -d node_modules ]]; then
  yarn
fi

cd $SITE_PATH
sudo systemctl reload php8.3-fpm

php$PHP_VERSION ./console.php assets:build:js
php$PHP_VERSION ./console.php assets:build:css
php$PHP_VERSION ./console.php assets:build:elfinder
php$PHP_VERSION ./doctrine.php orm:clear-cache:metadata --flush
php$PHP_VERSION ./doctrine.php orm:clear-cache:query --flush
php$PHP_VERSION ./doctrine.php orm:clear-cache:result --flush
php$PHP_VERSION ./doctrine.php orm:generate-proxies
```

**Comment by saeedvaziry** [comment]
Deployment failures only work when the command with a status other than 0 which Vito takes it as unsuccessful execution.
However in your case it exists with status 0 which is the reason Vito recognizes it as successful execution.

if you run git pull manually it will exit with status 1 but in a script, bash will execute it until the end and then returns the exit code of the latest statement (if I am not mistaken in the last part).

so one way would be to add shell if condition to see if the command wasn't successful and just exit with 1.

So you can adjust your script to something like the following:

```
cd $SITE_PATH

if ! git pull origin $BRANCH; then
    echo 'ERROR' && exit 1
fi

...
```

**Comment by Dennis4720** [comment]
That did it. Cheers. Ploi does this automatically do I thought it was a bug.

**Comment by saeedvaziry** [comment]
Will think how to improve it but not a high prio at the moment
