### ISSUE TITLE
Postgres 16 - Database Owner Not Set

### ISSUE THREAD

**Issue by devsarfo** [vitodeploy/vito#279]
**Describe the bug**
When you create a new database in Postgres 16 and assign a user to it, it uses **postgres** as the owner instead of the one set.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Server with Postgres as the DB
2. Go to databases 
3. Create a new database with a user
4. SSH into server 
5. Switch to  Postgres user using `sudo -i -u postgres`
6.  Access the PostgreSQL Command Line (psql) using `psql`
7. Run `\l` and observe the owner of the database you created

**Expected behaviour**
The Owner of the DB should be the one set in Vito and not posgres

**Screenshots**
Vito
![image](https://github.com/user-attachments/assets/d14571e8-cbc2-47fd-b458-0fca5f5c2623)

psql
![image](https://github.com/user-attachments/assets/8f52125d-dfdd-4651-a061-bc21cc4cdc44)

**Additional context**

**Comment by saeedvaziry** [comment]
Shouldn't postgres user own all the databases? and the other users just have access? kinda similar to root access on mysql.

**Comment by devsarfo** [comment]
The staging user is required to own staging for the Laravel migrations to work. When the owner is set to staging, postgres user still has access. The PostgreSQL superuser always has access to everything within the database, regardless of ownership. This is why even after setting the owner to "staging," the postgres user still has access.

I created a new db and added the user, as you can see below, it gives you the error.
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/80c56e55-3051-430c-8f8e-89f2fd24a35f">


<img width="821" alt="image" src="https://github.com/user-attachments/assets/7d71618a-f8ec-4561-8275-2cda6ee3fd93">


<img width="1770" alt="image" src="https://github.com/user-attachments/assets/73d0b970-5651-47aa-932a-cec7dbc102bb">

**Comment by abdasis** [comment]
I face this issue to

**Comment by saeedvaziry** [comment]
@devsarfo so if the staging user in your case should own the staging database when you link it, then other links will override this as its not possible that a db to have multiple owners.

**Comment by devsarfo** [comment]
@saeedvaziry That is correct. So, I did a bit of reading and discovered that this occurs in PostgreSQL v15 or higher. The default permissions on the public schema have changed in v15. Before, the insecure default was to allow everyone (PUBLIC) to create objects in the schema "public". Now, only the database owner can do that unless you grant extra privileges.

So when we link, we need to grant the linking user CREATE on the public. And that was the solution I had. For eg. GRANT CREATE ON SCHEMA public TO my_database_user;

Read more here: https://www.enterprisedb.com/blog/new-public-schema-permissions-postgresql-15

I am willing to test more on this if you still have any issues and raise the PR.

**Comment by saeedvaziry** [comment]
Alright, counting on your PR as I am not an expert on PostgreSQL :)

**Comment by devsarfo** [comment]
PR created - https://github.com/vitodeploy/vito/pull/339

**Comment by devsarfo** [comment]
Hi @saeedvaziry, updated here: https://github.com/vitodeploy/vito/pull/347

**Comment by saeedvaziry** [comment]
Can we close this one? @devsarfo
