### ISSUE TITLE
Install using docker does not work with bind mounts

### ISSUE THREAD

**Issue by PeterXQChen** [vitodeploy/vito#283]
**Describe the bug**
When the volume is updated to be a bind mount, it does not throw an error in the logs but when visiting the URL, you get a error 500. The issue seems to be that the vendor files do not get created/retrieved.

**To Reproduce**
Updated "volumes" to be a bind mount using relative path. Same issue with absolute path.

**Expected behavior**
All vendor files retrieved and saved to the bind mount path.

**Comment by saeedvaziry** [comment]
have you copied the content of the previously mounted volume to the new one?

**Comment by PeterXQChen** [comment]
> have you copied the content of the previously mounted volume to the new one?

It is a new install.

**Comment by PeterXQChen** [comment]
So I found a work around to this:

1. Start a new instance/container
2. Let everything finish setting up
3. Stop instance/container
4. Copy over all the contents into your desired bind mount path
5. Update docker compose to reference the new bind mount path
6. Start up instance/container

This seems to start up find as it has all of the ncessary files under /app and /framework folder.

**Comment by crosa7** [comment]
Same issue here

**Comment by saeedvaziry** [comment]
all necessary files that Vito needs (can be copied somewhere else) are in the storage folder.

anyways, I still cannot consider this as a bug of Vito.

Closing this as there is no actions to be taken
