### ISSUE TITLE
Documentation Typo - Notification Channels - Telegram

### ISSUE THREAD

**Issue by PeterXQChen** [vitodeploy/vito#286]
**Describe the bug**
"bot" is spelt "but" for the telegram section.

![image](https://github.com/user-attachments/assets/c332d3f9-e978-4f4e-a630-348cd5c0d8f2)

**Comment by saeedvaziry** [comment]
Thanks, Closing as it is not a Vito bug. Feel free to raise a PR to fix on https://github.com/vitodeploy/docs
