### ISSUE TITLE
UI glitch, maybe

### ISSUE THREAD

**Issue by ket-c** [vitodeploy/vito#289]
I think vito deploy has UI glitch or something is working well

When i click on deploy, it will still be showing 'deploying' even tho it is done(sometimes too it doesn't deploy at all)

When i click on uninstall at the service page, it is still showing 'uninstalling' for days now. Same applied to 'disabling'

It was working well but i think I started to experience this after i tried to install opcache in php 8.2

**Comment by saeedvaziry** [comment]
This might be because of rendering some parts of the page every few seconds using HTMX.

The issue will be fixed on VitoDeploy v2.

Closing this ticket as we won't fix it on v1.
