### ISSUE TITLE
Issue Adding New Server – Stuck on Initializing

### ISSUE THREAD

**Issue by lifelessrasel** [vitodeploy/vito#291]
I'm unable to add a new server as it’s stuck on "Initializing" or "Waiting for Provider." Could you please help me resolve this?

https://i.postimg.cc/Hsb4Q5bb/image.png
https://i.postimg.cc/XJhcgk2k/image.png

**Comment by saeedvaziry** [comment]
@lifelessrasel we need more info.

How did you install Vito? docker, local, VM...
