### ISSUE TITLE
Support for MySQL 8.4

### ISSUE THREAD

**Issue by saeedvaziry** [vitodeploy/vito#304]
### Discussed in https://github.com/vitodeploy/vito/discussions/227

<div type='discussions-op-text'>

<sup>Originally posted by **webard** June  4, 2024</sup>
Hello,
Newest version of MySQL is 8.3. Support for it would be nice.</div>

**Comment by joglomedia** [comment]
Hi,

The current LTS version of MySQL community edition is 8.4, 
Deb package available at https://dev.mysql.com/get/mysql-apt-config_0.8.32-1_all.deb

Unfortunately, this version only support Ubuntu 24.04 & 22.04

Should we add this version to Vito?
