### ISSUE TITLE
[Vito v2.x] The `create-user.sh` script incorrectly specifies /home/root/ as the root user's home directory

### ISSUE THREAD

**Issue by joglomedia** [vitodeploy/vito#312]
**Describe the bug**
This is not bug, just minor improvement required

**To Reproduce**
1. Go to 'Servers'
2. Click on 'Create Server'
3. Chose 'Custom'
4. Fill up all required fields
5. Click on `Create` button
6. See logs

**Expected behavior**
No 

**Screenshots**
Server creation

Server creation event log `xxxxx-create-user.log`
![image](https://github.com/user-attachments/assets/ba56d38b-5f2d-4140-a152-5b86ac5833c2)

**Additional context**
The `create-user.sh` script incorrectly specifies `/home/root/` as the root user's home directory. In Ubuntu, the `root` user's home directory is `/root`.

**Comment by saeedvaziry** [comment]
Its not a bug. it adds the key on both users

**Comment by joglomedia** [comment]
> Its not a bug. it adds the key on both users

Yes, but the Ubuntu root directory is misplaced, it should be only `/root/`
