### ISSUE TITLE
[Vito v2.x] Connect to a Source Control Failed: `SQLSTATE[22P02]: Invalid text representation ...`

### ISSUE THREAD

**Issue by joglomedia** [vitodeploy/vito#314]
**Describe the bug**
An error occurred while connecting to the Source Control provider due to a SQL issue.

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type json DETAIL: 
```

**To Reproduce**
1. Go to 'Source Controls' menu
2. Click on 'Connect' button
3. Select the provider 'Github'
4. Enter your `Name` and `API Key`
5. Click on 'Connect'
6. See the error

**Expected behavior**
Successfully connect to source control and save the data to table.

**Screenshots**
![image](https://github.com/user-attachments/assets/dfe31f3d-b160-4850-8fe4-7eb984ad1d46)

**Additional context**
It appears there's a data type mismatch. The `provider_data` column is defined as a JSON type, but the stored data is actually an `encrypted:array` represented as a string.

**Comment by saeedvaziry** [comment]
Cannot reproduce the issue.

**Comment by saeedvaziry** [comment]
are you using Postgresql as VitoDeploy's database?

**Comment by joglomedia** [comment]
> are you using Postgresql as VitoDeploy's database?

Yes, I am using PostgreSQL 16

**Comment by saeedvaziry** [comment]
Vito itself only supports SQLite as database. any other database usage is not supported and issues will not be fixed.
