### ISSUE TITLE
[Vito v2.x] The installation script is still referencing v1.x (latest release tag `1.11.0`)

### ISSUE THREAD

**Issue by joglomedia** [vitodeploy/vito#320]
**Describe the bug**
Auto install v2.x installation failed. The installation script from `scripts/install.sh` is still referencing v1.x (latest release tag `1.11.0`)

**To Reproduce**
1. Create 'Ubuntu' instance from your vps/cloud server provider (I use Amazon Lightsail)
2. Execute `bash <(curl -Ls https://raw.githubusercontent.com/vitodeploy/vito/2.x/scripts/install.sh)`
3. See the installed VitoDeploy is version 1.x

**Expected behavior**
Running `scripts/install.sh` from v2.x should install Vito v2.x latest release

**Additional context**
The Git branching currently references a tag from the latest merged commit, but there's no released tag for v2.x.

`V_GIT_BRANCH=$(git tag -l --merged "${VITO_VERSION}" --sort=-v:refname | head -n 1)`

**Comment by saeedvaziry** [comment]
branch 2.x doesn't have a release yet!
