### ISSUE TITLE
View logs return 302 status code

### ISSUE THREAD

**Issue by AiAe** [vitodeploy/vito#333]
**Describe the bug**
When I try to view any logs in Vito, they all return 302 status code.

**To Reproduce**
1. Select server
2. From overview click on the eye icon on any of the logs after server is created.

**Expected behavior**
I expect to see the logs from the command it ran

**Screenshots**
![CleanShot 2024-11-01 at 3  19 26](https://github.com/user-attachments/assets/11cc104d-714e-4411-9e39-c8aeb0fa3da2)

**Additional context**
Vito version: 1.11.0
Provider: Hetzner

Vito runs under docker

**Comment by saeedvaziry** [comment]
302 is expected. it's a HTMX call which is being shown as 302 with the log content in the session.

if you see empty page then means there is no logs in the log file or the log file missing
