### ISSUE TITLE
Docker Start Script fails Due to Missing Folders

### ISSUE THREAD

**Issue by eznix86** [vitodeploy/vito#343]
**Describe the bug**

I tried to run vitodeploy via docker swarm, then I've got "Please provide a valid cache path."

**To Reproduce**
1. Copy paste this docker-compose: https://vitodeploy.com/introduction/installation.html#docker-compose
2. Replace necessary environment, and additionally add APP_ENV=local APP_DEBUG=True
3. There should be no prior volumes, should start fresh.
4. After few seconds should show: "Please provide a valid cache path."

**Expected behavior**
Should run right away.

**Screenshots**
<img width="484" alt="Screenshot 2024-11-04 at 19 20 42" src="https://github.com/user-attachments/assets/e53a8556-b667-4fc3-a8b1-92ca225b38b5">

**Additional context**
Manage to fixed by doing 

```sh
cd storage/
mkdir -p framework/{sessions,views,cache}
chown -R www-data:www-data framework
```

Maybe we could add it directly in start.sh

**Comment by saeedvaziry** [comment]
closing as discussed here #345
