### ISSUE TITLE
Failed to install ufw on Ubuntu 20 LTS

### ISSUE THREAD

**Issue by eznix86** [vitodeploy/vito#344]
**Describe the bug**
While installing a custom vps server via ssh, installing ufw failed.

**To Reproduce**
1. Create new Server 
2. Fill in The Form
3. Select Ubuntu 20 LTS
4. Webserver nginx Database postgresql 16
5. Press Create Server
6. Wait for the install-ufw step
7. See error

**Expected behavior**
Should install ufw and complete the progress.

**Screenshots**
<img width="1143" alt="Screenshot 2024-11-04 at 20 10 56" src="https://github.com/user-attachments/assets/de3e7c99-1f19-48b8-a9c4-756d6158603b">

**Additional context**
I believe `ufw` is not installed by default on Ubuntu 20 LTS, so maybe in the `install-dependencies.sh` we should append `ufw`

**Comment by saeedvaziry** [comment]
ufw is being installed in another script. you can see in your screenshot (installing-ufw) why we should put it into `install-dependencies.sh` too?

**Comment by eznix86** [comment]
The installation failed, and when I reviewed the script at [this link](https://github.com/vitodeploy/vito/blob/1.x/app/SSH/Services/Firewall/scripts/ufw/install-ufw.sh#L1), I noticed that it doesn’t include `apt install ufw`. I also checked the server, and `ufw` wasn’t installed.

So this PR installs ufw to dependencies
