### ISSUE TITLE
How to uninstall Vito? 

### ISSUE THREAD

**Issue by freehzw** [vitodeploy/vito#349]
I installed Vito in vps, and it conflicts with my original LNMP environment, causing nginx to not work properly. How do I uninstall Vito?

**Comment by eznix86** [comment]
Not sure if it is a but, but it is undocumented.

Maybe give this a try:

Script available here: https://gist.github.com/eznix86/e473ee00d6169102adf04bde680dfbdc

Convenient script:

```sh
bash <(curl -Ls https://gist.githubusercontent.com/eznix86/e473ee00d6169102adf04bde680dfbdc/raw/0ec80c3ba123402f7b599c41af5a574ab48e327e/uninstall-vitodeploy.sh)
```

**Comment by freehzw** [comment]
thank you.

**Comment by eznix86** [comment]
@freehzw any update? Was it fully removed, are you satisfied, it you do i can turn this into a PR

**Comment by saeedvaziry** [comment]
To install VitoDeploy on a virtual machine it is required to have a fresh ubuntu server and to uninstall you just need to delete the server and recreate it. So it doesn't support or recommend uninstallation out of the box.
