### ISSUE TITLE
Provider Error: error during placement

### ISSUE THREAD

**Issue by emrancu** [vitodeploy/vito#35]
I am trying to create server from hetzner but show error `Provider Error: error during placement`

I follow:
https://docs.hetzner.com/cloud/api/getting-started/generating-api-token/

**Comment by emrancu** [comment]
Issue resolved. 

Issue was: I select hetzner plan  but that plan not exist on the region.

Thank you @saeedvaziry for fantastic solution❤️

**Comment by saeedvaziry** [comment]
Happy that it worked. Although the plans need to be updated on Vito core configurations. they're pretty old now.
