### ISSUE TITLE
Viewing scripts logs is always blank

### ISSUE THREAD

**Issue by eznix86** [vitodeploy/vito#350]
**Describe the bug**
The feature where we press an eye to view logs is blank

**To Reproduce**
There is several area where it is blank:
- Select Server > Sidebar, Overview, On Logs, Press the eye, blank
- Select Server > Sidebar, Logs > Press the eye, blank
- Scripts > Create Script > Execute Script > Press eye, Executions, Press eye, to see logs, blank
- Select Server > Side Bar, Sites > Show Site > Deployments, Press eye, blank

**Expected behavior**
- Should display logs of overview of the server
- Should display scripts output after execution, even on failure.
- Should display deployment output after execution, even on failure.

**Screenshots**
<img width="900" alt="Screenshot 2024-11-05 at 18 14 16" src="https://github.com/user-attachments/assets/6d437b7e-8860-4f39-998a-2366bb513a1e">

**Comment by eznix86** [comment]
fixed after rebuilding the container, but after restarting server its back.

**Comment by saeedvaziry** [comment]
Will close the issue if there is no proposed fix for it
