### ISSUE TITLE
Node JS Version

### ISSUE THREAD

**Issue by Afan417** [vitodeploy/vito#40]
Trying to install a site that requires Node JS version v18, but by default Vito installs Node v12, I changed the node version manually on the site/VPS that Vito created using nvm but it still shows me the v12 version, any help?

Deployment script, just to test version and try to install node packages:
```
npm --version
node --version

npm install
```

Result
```
8.5.1
v12.22.9
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'laravel-vite-plugin@0.7.8',
npm WARN EBADENGINE required: { node: '>=14' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'postcss-import@15.1.0',
npm WARN EBADENGINE required: { node: '>=14.0.0' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'postcss-load-config@4.0.1',
npm WARN EBADENGINE required: { node: '>= 14' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'rollup@3.28.1',
npm WARN EBADENGINE required: { node: '>=14.18.0', npm: '>=8.0.0' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'tailwindcss@3.3.3',
npm WARN EBADENGINE required: { node: '>=14.0.0' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'vite@4.4.9',
npm WARN EBADENGINE required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'yaml@2.3.1',
npm WARN EBADENGINE required: { node: '>= 14' },
npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 119 packages in 2s

20 packages are looking for funding
run `npm fund` for details

found 0 vulnerabilities
```

Actual node version of the site/VPS of the site I'm trying to install (logged in as SSH):

![image](https://github.com/vitodeploy/vito/assets/45122414/3e633556-189c-4ac6-84c7-bde5b4c84d03)

**Comment by noor1yasser9** [comment]
### **Install or Verify NVM**
Ensure that NVM is installed or install it if it's not already present.
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`
Close and reopen your terminal or run `source ~/.bashrc` (or `source ~/.zshrc` if using Zsh) to load NVM.

### **Install Node.js v18**
`nvm install 18`

### **Switch to Node.js v18**
`nvm use 18`

finally, confirm that Node.js v18 is now active

**Comment by Afan417** [comment]
Figured it out, just had to clean the cache & re-install using stable version and it worked fine 🤦 

For anyone wondering, these were the commands I ran and worked:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable 
```

Cheerss

**Comment by saeedvaziry** [comment]
Still a good idea to update the installer to install the newer version of Node

**Comment by saeedvaziry** [comment]
Update:

Vito already installing the latest stable version of the Node.js

I tried to reproduce the issue but couldn't. for me installed the version 18

https://github.com/vitodeploy/vito/blob/main/resources/commands/installation/install-nodejs.sh#L1
