### ISSUE TITLE
Herd fresh installation: error on SSH

### ISSUE THREAD

**Issue by marco-introini** [vitodeploy/vito#42]
Hello
I followed instructions here: https://vitodeploy.com/introduction/installation.html#laravel-herd-or-valet for setting up VitoDeploy on my machine using Herd

When I try to create a server I get this error:

file_get_contents(): Read of 8352 bytes failed with errno=21 Is a directory

The problem is here:

```php
@php

    $key = str(file_get_contents(storage_path(config('core.ssh_public_key_name'))))->replace("\n", "");

@endphp
```

I've seen that the .env.example missed some values:

```
SSH_PUBLIC_KEY_NAME=ssh-public.key
SSH_PRIVATE_KEY_NAME=ssh-private.pem
```

When I add them I get a fine not found exception

I think the documentation missed some points:
- may I need to create a new ssh key for VitoDeploy?
- should I put it inside strorage?

Thanks a lot for your work!

**Comment by saeedvaziry** [comment]
I guess I forgot to mention this in the documentation!
To connect to the server you need to generate an SSH key pair on your local like the [installation](https://github.com/vitodeploy/vito/blob/main/install/install.sh#L198) on VPS.

```sh
openssl genpkey -algorithm RSA -out /PATH_TO_VITO/storage/ssh-private.pem
chmod 600 /PATH_TO_VITO/storage/ssh-private.pem
ssh-keygen -y -f /PATH_TO_VITO/storage/ssh-private.pem > /PATH_TO_VITO/storage/ssh-public.key
```

**Comment by marco-introini** [comment]
Thank you so much!
It works
