### ISSUE TITLE
Website Backup to S3

### ISSUE THREAD

**Issue by Danny159** [vitodeploy/vito#46]
I love this project!

Would it be possible to add some sort of backup of sites / apps to S3.

Thanks!

**Comment by saeedvaziry** [comment]
Do you mean to backup the files of a website? Why not just use cloud storage like S3 for the storage part of the app?

And keep the source code on git.

Laravel supports plenty of storage drivers

https://laravel.com/docs/10.x/filesystem

**Comment by Danny159** [comment]
Hey!

I mostly meant for easy restore of projects... and for MySQL... but I guess MySQL could be backuped using Laravel...

Just thought if I had say 15 apps running at one time, would make restoring easy for settings etc.

Thanks

**Comment by saeedvaziry** [comment]
I get that.

At the moment Vito supports only Database Backups
