### ISSUE TITLE
The installation has been failed on step: Installing ufw (100%)

### ISSUE THREAD

**Issue by Danny159** [vitodeploy/vito#49]
I am trying to add a new server. VPS Ubuntu 22.04 clean install.

I get the following error right at the end of the Installation on Vito

> The installation has been failed on step: Installing ufw (100%)

The log file contains the following:

install-ufw
> Default incoming policy changed to 'deny' (be sure to update your rules accordingly) Default outgoing policy changed to 'allow' (be sure to update your rules accordingly) Rules updated Rules updated Rules updated Firewall is active and enabled on system startup

ufw-status
> ○ ufw.service - Uncomplicated firewall Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled) Active: inactive (dead) Docs: man:ufw(8)

-----

I tried to troubleshoot by installing ufw using SSH, however, still the same error...

**Comment by saeedvaziry** [comment]
Have you tried to reinstall it again? I will try to install and reproduce the issue

**Comment by Danny159** [comment]
Yes I've done it a few times. Still same issue. I don't mind giving you access if you need it.

**Comment by saeedvaziry** [comment]
could you please tell me how much resources you have on your VPS and what is the provider?

I was able to install on 2GB memory and 1 CPU on Hetzner provider.

**Comment by Danny159** [comment]
https://vpsdime.com

4 vCPU / 6GB RAM

**Comment by saeedvaziry** [comment]
If you don't mind please share the credentials so I can check.

sa.vaziry@gmail.com

**Comment by Danny159** [comment]
Hi

It's not installing Vito. It's adding the clean server to Vito.

Thanks

**Comment by saeedvaziry** [comment]
I was able to reproduce it

```
● ufw.service - Uncomplicated firewall
     Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
     Active: active (exited) since Tue 2023-09-12 08:48:31 UTC; 5min ago
       Docs: man:ufw(8)
   Main PID: 493 (code=exited, status=0/SUCCESS)
        CPU: 2ms

Sep 12 08:48:31 Ubuntu-2204-jammy-64-minimal systemd[1]: Starting Uncomplicated firewall...
Sep 12 08:48:31 Ubuntu-2204-jammy-64-minimal systemd[1]: Finished Uncomplicated firewall.
```

Despite the status of the `ufw` the functionality works and I was able to add or remove rules.

But will look into it

**Comment by saeedvaziry** [comment]
and what do you see in the Vito's logs?

You can find the logs in storage/logs folder of your Vito instance

**Comment by Danny159** [comment]
There is no logs in the logs folder on Vito. I have tried to install the server again today but now run into an error.

In the server-logs folder within storage, I see the following in the "13-1694637215-install-ufw.log" file:

> sudo: ufw: command not found

**Comment by Danny159** [comment]
I also get the following when I install ufw manually... then try and add the server...

> ○ ufw.service - Uncomplicated firewall Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled) Active: inactive (dead) Docs: man:ufw(8)

**Comment by saeedvaziry** [comment]
If you're trying to reinstall it in the same server I don't think that can work.

But again, I don't think thats the issue of the ufw. UFW is the last step but after that Vito updates the server installation status to 100% so if ufw fails it cannot update it to 100%. my point is something happening after updating the state which should be visible in the logs if any errors happening.

**Comment by shuguroff** [comment]
I got same issue. 

Steps to solve problem:

1) Install Ubuntu 22
2) apt-get update
3) apt-get upgrade
4) add ssh certificate
5) add server in vito

**Comment by saeedvaziry** [comment]
@shuguroff 
It is most probably related to the resources. Please make sure that the server you are creating has 1 GB or more memory and 1 CPU or more

**Comment by Danny159** [comment]
@shuguroff what is your command to add the add ssh certificate please from lets encrypt?

Thanks

**Comment by shuguroff** [comment]
If you ask about step 5, I told about ssh certificate to access to server (ssh-keygen -t rsa).

**Comment by saeedvaziry** [comment]
I think this might be related to #107 but if the error still happening please open a new issue.
