### ISSUE TITLE
Add options for changing PHP file upload limit and maximum process run time

### ISSUE THREAD

**Issue by tanbinislam** [vitodeploy/vito#54]
Hi,
Recently i was trying to change php maximum post size and max execution time by editing the ini file. But could no locate nginx config file for client maximum body size. I was trying to import a database about 40MB in size via phpMyAdmin. It would be nice to have a ui for this.

**Comment by saeedvaziry** [comment]
You can already do this 

https://vitodeploy.com/servers/php.html#edit-php-ini

<img width="403" alt="image" src="https://github.com/vitodeploy/vito/assets/61919774/531d6505-53da-4039-ba15-4ec2d24b63d4">

**Comment by tanbinislam** [comment]
![image](https://github.com/vitodeploy/vito/assets/17528515/07b71a49-7d2d-460c-9636-c7679447edca)


![image](https://github.com/vitodeploy/vito/assets/17528515/9eb52b2f-f860-4f21-9d6b-a71e5e052465)

This i what i get when try to import gatabase via phpmyadmin. db file size is 35MB and php.ini post_max_size = 128M

**Comment by saeedvaziry** [comment]
How did you install the phpmyadmin? if using nginx maybe you need to also restart the nginx after changing the php.ini

**Comment by tanbinislam** [comment]
Installed phpMyadmin with github. Restarting nginx is not the fix. **Can youplease add the ability to edit the site nginx file so that the value of client_max_body_size configuration can be updated or added.**

**Comment by saeedvaziry** [comment]
being able to modify the site's nginx config file would be good option

**Comment by saeedvaziry** [comment]
Added to the roadmap

https://features.vitodeploy.com/submissions/65930b770be3e19e943a2e4c
