### ISSUE TITLE
No Default VPC to (truncated...)

### ISSUE THREAD

**Issue by corean** [vitodeploy/vito#55]
Create New Server Problem in AWS 

I understand that when deploying an application on AWS, a VPC must be set up.
Currently, I seem to be getting a No Default VPC.

```
[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://ec2.ap-northeast-2.amazonaws.com` resulted in a `400 Bad Request` response:
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Response><Errors><Error><Code>VPCIdNotSpecified</Code><Message>No default VPC fo (truncated...)
 at /home/vito/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
```

**Comment by saeedvaziry** [comment]
Could you please provide more info so I can reproduce?
Like what kind of instance and what size or plan?
And this happens on which step? Server installation?

**Comment by corean** [comment]
Oh, I'm currently trying to register with the minimum plan after selecting "AWS" in "Create Server".

![스크린샷 2023-09-20 17 47 09](https://github.com/vitodeploy/vito/assets/225376/30e55f08-5718-40b6-8848-4e4d5c476bed)

**Comment by saeedvaziry** [comment]
I was able to reproduce the issue. sounds like a bug. will see what is going on

**Comment by saeedvaziry** [comment]
After checking this through looks like we have only ubuntu 18 and ubuntu 20's image ids in the configuration files.

That means at the moment you can use AWS only with ubuntu 20 operating system until we add the image ids for ubuntu 22 for different regions.

**Comment by saeedvaziry** [comment]
This should be solved by now. Please update
