### ISSUE TITLE
Install PHP extensions

### ISSUE THREAD

**Issue by saeedvaziry** [vitodeploy/vito#6]
Vito should be able to install some PHP extensions on the PHP page.

**Comment by marco-introini** [comment]
My vote for this feature!
You're doing such a wonderful work!

**Comment by saeedvaziry** [comment]
If you look at the jobs and commands you will see that everything is ready for this feature. Just need to do some UI to enable it.

**Comment by arzola** [comment]
@saeedvaziry I want to create a plugin for this for the 3.x I'm just trying to understand how extensions are being managed right now? are you using docker under the hoods?, PECL? I see you call `install-php-extension-extensionName`

**Comment by saeedvaziry** [comment]
@arzola this is how vito installs php extensions

https://github.com/vitodeploy/vito/blob/3.x/resources/views/ssh/services/php/install-php-extension.blade.php
