### ISSUE TITLE
Can locally installed instance manage local servers

### ISSUE THREAD

**Issue by otengkwame** [vitodeploy/vito#64]
Hi @saeedvaziry I have been trying to run Vito locally but it seems I'm finding my way out. 

Let me add a screenshot here:
![Screenshot from 2023-09-30 17-06-06](https://github.com/vitodeploy/vito/assets/3446150/c161194f-8586-47fc-9ba2-056f1e3a45a7)

It is that I am doing something wrong that's why I have that warning message?

My use case is, can I use it to install a server on the same local machine, if so how will I configure the SSH details.

Thank You

**Comment by saeedvaziry** [comment]
Hi,
The target machine cannot be the same machine that Vito is running on it.
Vito will prevent server creations for these IPs ('127.0.0.1', 'localhost', '0.0.0.0')

**Comment by otengkwame** [comment]
Oh ok great, that means on a local network it is very possible to manage another server for instance let's say 192.168.0.1 is the server Vito is on, and I have a server with IP 192.168.0.2, it should work without any issues right?

**Comment by saeedvaziry** [comment]
Yes it is possible
