### ISSUE TITLE
Add PHP 8.3

### ISSUE THREAD

**Issue by saeedvaziry** [vitodeploy/vito#69]
Add php8.3 support

**Comment by saravanasai** [comment]
Hi  @saeedvaziry. I am working on this feature can i change the default selection to PHP 8.3 on server creation?

**Comment by saravanasai** [comment]
Hi @saeedvaziry. I have tried to run that install-php.sh file. It installing php8.3 but I am getting these error messages. I have no idea where I have to install these unfound packages. 
```
E: Unable to locate package php8.3-mcrypt
E: Couldn't find any package by glob 'php8.3-mcrypt'
E: Unable to locate package php8.3-redis
E: Couldn't find any package by glob 'php8.3-redis'
```

**Comment by saravanasai** [comment]
@saeedvaziry Thanks. Let me wait then. I have tried to find to add support for Pgsql. I do have not that much use for Pgsql. I have checked with a friend who works on the DevOps team. He said that there are multiple versions. 

Any future idea & scops to implement it

**Comment by saravanasai** [comment]
> @saravanasai I add php8.3 in my forked repo and I test it there's some info : the **php8.3-mcrypt** is not work, you should remove it from the commands/php/install-php.sh file

@elmarzouguidev  I don't removing those dependencies is good. Let's wait for  php8.3-mcrypt official release then we can add this feature to the project.

**Comment by saeedvaziry** [comment]
Added to the roadmap

https://features.vitodeploy.com/submissions/65930ba90be3e19e943a793d
