### ISSUE TITLE
Lack of user_id column in notification channels table

### ISSUE THREAD

**Issue by haipham** [vitodeploy/vito#70]
Notification channels table does not have 'user_id', need more improve notification channels to support other channel, as Vonage, Telegram bot...

Thank you for your hard work.

**Comment by saeedvaziry** [comment]
Thanks for the feedback. Yes at the moment Vito doesn't focus on the multi-user features but it has been designed to be able to do so in the future.
Marking this as a feature.

**Comment by saeedvaziry** [comment]
Added to the roadmap

https://features.vitodeploy.com/submissions/659305310be3e19e94324897
