### ISSUE TITLE
What will be the username and password of ssh of server.

### ISSUE THREAD

**Issue by mrthito** [vitodeploy/vito#73]
Example my IP is 123.123.456.789
Than, I want something like username@<ip address> and Password to access that

I am using Linode

**Comment by saeedvaziry** [comment]
Default username to your Vito server is 'vito'

And the password is being generated and printed when the installation finishes

**Comment by mrthito** [comment]
Are you telling about SSH or vito admin account?

**Comment by saeedvaziry** [comment]
So for the server that you installed Vito on it's the one I explained.

For the servers that Vito provisions, it creates a user with the username of `vito` and a random password and stores the password encrypted into the database. At the moment you cannot read that password but to access the server via SSH you can deploy an SSH Key into that server using Vito and then SSH to it without a password.
