### ISSUE TITLE
cant add sites 

### ISSUE THREAD

**Issue by muadhoonya** [vitodeploy/vito#79]
cant add sites

**Comment by saeedvaziry** [comment]
@muadhoonya Could you please elaborate? what errors do you see? any screenshot? you can find the logs in the storage/logs folder of your Vito instance.

**Comment by muadhoonya** [comment]
it gets internal server error. Do you plan to add wordpress installation during site add? btw script is awesome

**Comment by muadhoonya** [comment]
i think its good to desable github option while adding php sites

**Comment by saeedvaziry** [comment]
Regarding the current problem you're facing, would be good if you can post the log file here.

Regarding Wordpress, There is a plan to add it for sure.

And regarding disabling source-control for PHP sites, at the moment for the sake of deployments it is easier to use a source-control but will consider to see any possible support uploading source code directly to the server.

**Comment by saeedvaziry** [comment]
@muadhoonya Vito now deploys WordPress!

**Comment by muadhoonya** [comment]
@saeedvaziry Great Thank you sir
