### ISSUE TITLE
Cannot connect to 176.58.x.x:port . Error 111. Connection refused  -- when i change ssh port from 22 to xxxx

### ISSUE THREAD

**Issue by elmarzouguidev** [vitodeploy/vito#81]
Cannot connect to 176.58.x.x:port . Error 111. Connection refused  -- when i change ssh port from 22 to xxx

{"exception":"[object] (phpseclib3\\Exception\\UnableToConnectException(code: 0): 

Cannot connect to 176.58.x.x:port . Error 111. Connection refused at 

/home/uuuser/local/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1336)

**Comment by saeedvaziry** [comment]
@elmarzouguidev the installation on port 22 worked and then you changed the port and stopped working?

**Comment by elmarzouguidev** [comment]
@saeedvaziry Yes, but I found the problem : 

the problem is coming from the shared hosting, when I install VITO it's denied some port by default in the firewall

**Comment by saeedvaziry** [comment]
@elmarzouguidev exactly! it only whitelists 22, 80 and 443
