### ISSUE TITLE
Need File Manager

### ISSUE THREAD

**Issue by aminulalzaf** [vitodeploy/vito#93]
Its really a grate project. I would like to request for file manager feature for modifying file.

Thanks

**Comment by saeedvaziry** [comment]
Thanks for the feedback,
Please add the requested feature into the board
https://vitodeploy.featurebase.app

**Comment by saeedvaziry** [comment]
However, VitoDeploy is a server management that manages your server remotely. it is not being installed in the target servers but it is being installed in a separate server to manage your other servers. That being said, It handles the target servers via SSH so it wouldn't make sense to manage the target server's files via SSH.
But I can consider a service like PHPMyAdmin to install it directly into your target servers via VitoDeploy so you can manage your files safely.
